name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: chy9002/mark-idea
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag chy9002/mark-idea:$(date +%s)
